name:                dmn

# add pretty print under dependencies later

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- prettyprinter
- hxt

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  dmn-exe:
    main:                Main.hs
    source-dirs:         src
    dependencies:
    - dmn

