name:                dmn

# add pretty print under dependencies later

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- prettyprinter
- hxt
- split
- containers
- optics
- text
- mtl
- aeson
- haskeline
- megaparsec
- parser-combinators

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -XDerivingStrategies
- -XDerivingVia
- -XOverloadedRecordDot
- -XOverloadedStrings
- -XOverloadedLabels

library:
  source-dirs: 
  - .
  - simala/src

executables:
  dmn-exe:
    main:                Main.hs
    source-dirs:         src
    other-modules:
    - ConvertDMN
    - FromMD
    - PrintProg
    - TranslateToSimala
    - TypeChecking
    - Types
    dependencies:
    - dmn

tests:
  myproject-test:
    main:                Spec.hs
    source-dirs:        test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dmn
    - hspec
  
packages:
- .
- location:
    directory: simala/src