name:                dmn

# add pretty print under dependencies later

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- prettyprinter
- hxt
- split


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: .

executables:
  dmn-exe:
    main:                Main.hs
    source-dirs:         src
    dependencies:
    - dmn

tests:
  myproject-test:
    main:                Spec.hs
    source-dirs:        test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dmn
    - hspec
  